/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'patient' : null } |
  { 'superAdmin' : null } |
  { 'labAdmin' : null } |
  { 'phlebotomist' : null };
export interface Hospital {
  'id' : string,
  'area' : string,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'address' : string,
  'contactNumber' : string,
}
export interface HospitalPhlebotomistAssignment {
  'assignedAt' : bigint,
  'assignedBy' : Principal,
  'isActive' : boolean,
  'hospitalId' : string,
  'removedAt' : [] | [bigint],
  'removalReason' : [] | [string],
  'phlebotomist' : Principal,
}
export interface Settlement {
  'settlementType' : { 'Partial' : null } |
    { 'Settled' : null },
  'hospitalId' : string,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'amount' : bigint,
}
export type SystemMode = { 'production' : null } |
  { 'test' : null };
export type TestError = { 'notFound' : null } |
  { 'duplicateCode' : null };
export interface TestInput {
  'code' : string,
  'name' : string,
  'sampleType' : string,
  'isActive' : boolean,
  'price' : bigint,
}
export interface TestOutput {
  'id' : string,
  'code' : string,
  'name' : string,
  'sampleType' : string,
  'isActive' : boolean,
  'price' : bigint,
}
export interface UserProfile {
  'appRole' : AppRole,
  'area' : [] | [string],
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / HOSPITAL MANAGEMENT
   */
  'addHospital' : ActorMethod<
    [string, string, string, string, string],
    Hospital
  >,
  'addTest' : ActorMethod<
    [TestInput],
    { 'ok' : TestOutput } |
      { 'err' : TestError }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPhlebotomistToHospital' : ActorMethod<
    [string, Principal],
    HospitalPhlebotomistAssignment
  >,
  'bulkAddTests' : ActorMethod<[Array<TestInput>], Array<TestOutput>>,
  'disableHospital' : ActorMethod<[string], Hospital>,
  'disableTest' : ActorMethod<[string], TestOutput>,
  'getAllTests' : ActorMethod<[], Array<TestOutput>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHospitalById' : ActorMethod<[string], Hospital>,
  'getHospitals' : ActorMethod<[[] | [string]], Array<Hospital>>,
  'getHospitalsByPhlebotomist' : ActorMethod<[Principal], Array<string>>,
  'getPhlebotomistsByHospital' : ActorMethod<[string], Array<Principal>>,
  'getSettlementHistory' : ActorMethod<[string], Array<Settlement>>,
  'getSystemMode' : ActorMethod<[], SystemMode>,
  'getTest' : ActorMethod<[string], [] | [TestOutput]>,
  'getTestByCode' : ActorMethod<[string], [] | [TestOutput]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markSettlement' : ActorMethod<
    [
      string,
      bigint,
      { 'Partial' : null } |
        { 'Settled' : null },
      [] | [string],
    ],
    Settlement
  >,
  'removePhlebotomistFromHospital' : ActorMethod<
    [string, Principal, string],
    HospitalPhlebotomistAssignment
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSystemMode' : ActorMethod<[SystemMode], undefined>,
  'setTestStatus' : ActorMethod<
    [string, boolean],
    { 'ok' : TestOutput } |
      { 'err' : TestError }
  >,
  'updateHospital' : ActorMethod<
    [string, string, string, string, string, string],
    Hospital
  >,
  'updateTest' : ActorMethod<
    [string, TestInput],
    { 'ok' : TestOutput } |
      { 'err' : TestError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];