/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Hospital = IDL.Record({
  'id' : IDL.Text,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const TestInput = IDL.Record({
  'mrp' : IDL.Nat,
  'lab_cost' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'sampleType' : IDL.Text,
  'isActive' : IDL.Bool,
  'commission_amount' : IDL.Nat,
  'profit' : IDL.Nat,
  'price' : IDL.Nat,
});
export const TestOutput = IDL.Record({
  'id' : IDL.Text,
  'mrp' : IDL.Nat,
  'lab_cost' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'sampleType' : IDL.Text,
  'isActive' : IDL.Bool,
  'commission_amount' : IDL.Nat,
  'profit' : IDL.Nat,
  'price' : IDL.Nat,
});
export const TestError = IDL.Variant({
  'notFound' : IDL.Null,
  'duplicateCode' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Principal = IDL.Principal;
export const HospitalPhlebotomistAssignment = IDL.Record({
  'assignedAt' : IDL.Int,
  'assignedBy' : Principal,
  'isActive' : IDL.Bool,
  'hospitalId' : IDL.Text,
  'removedAt' : IDL.Opt(IDL.Int),
  'removalReason' : IDL.Opt(IDL.Text),
  'phlebotomist' : Principal,
});
export const SampleTestItem = IDL.Record({
  'testCode' : IDL.Text,
  'testName' : IDL.Text,
  'price' : IDL.Nat,
  'testId' : IDL.Text,
});
export const SampleInput = IDL.Record({
  'tests' : IDL.Vec(IDL.Opt(SampleTestItem)),
  'deliveryMethod' : IDL.Opt(IDL.Text),
  'hospitalId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'patientName' : IDL.Text,
  'paymentType' : IDL.Text,
  'createdByMobile' : IDL.Text,
  'phone' : IDL.Text,
});
export const AppTask = IDL.Record({
  'status' : IDL.Text,
  'patient_name' : IDL.Text,
  'hospital_id' : IDL.Text,
  'task_id' : IDL.Text,
  'created_at' : IDL.Int,
  'assigned_by' : IDL.Text,
  'assigned_to_mobile' : IDL.Text,
});
export const AppUser = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'assignedHospitalId' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'mobile' : IDL.Text,
});
export const SampleRecord = IDL.Record({
  'status' : IDL.Text,
  'tests' : IDL.Vec(SampleTestItem),
  'createdAt' : IDL.Int,
  'deliveryMethod' : IDL.Opt(IDL.Text),
  'hospitalId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'patientName' : IDL.Text,
  'paymentType' : IDL.Text,
  'createdByMobile' : IDL.Text,
  'phone' : IDL.Text,
  'sampleId' : IDL.Text,
});
export const AppRole = IDL.Variant({
  'patient' : IDL.Null,
  'superAdmin' : IDL.Null,
  'labAdmin' : IDL.Null,
  'phlebotomist' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'area' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardMetrics = IDL.Record({
  'pendingReports' : IDL.Nat,
  'revenueToday' : IDL.Nat,
  'samplesToday' : IDL.Nat,
  'samplesTotal' : IDL.Nat,
  'collectionsToday' : IDL.Nat,
  'activeHospitals' : IDL.Nat,
});
export const Settlement = IDL.Record({
  'settlementType' : IDL.Variant({
    'Partial' : IDL.Null,
    'Settled' : IDL.Null,
  }),
  'hospitalId' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const SystemMode = IDL.Variant({
  'production' : IDL.Null,
  'test' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHospital' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Hospital],
      [],
    ),
  'addTest' : IDL.Func(
      [TestInput],
      [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPhlebotomistToHospital' : IDL.Func(
      [IDL.Text, Principal],
      [HospitalPhlebotomistAssignment],
      [],
    ),
  'bulkAddTests' : IDL.Func([IDL.Vec(TestInput)], [IDL.Vec(TestOutput)], []),
  'createSample' : IDL.Func([SampleInput], [IDL.Text], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AppTask],
      [],
    ),
  'deleteAllData' : IDL.Func([], [], []),
  'deleteAllSampleData' : IDL.Func([], [IDL.Nat], []),
  'deleteAllTasks' : IDL.Func([], [IDL.Nat], []),
  'deleteTestUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'disableHospital' : IDL.Func([IDL.Text], [Hospital], []),
  'disableTest' : IDL.Func([IDL.Text], [TestOutput], []),
  'getAllAppUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
  'getAllSamples' : IDL.Func([], [IDL.Vec(SampleRecord)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(AppTask)], ['query']),
  'getAllTests' : IDL.Func([], [IDL.Vec(TestOutput)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getHospitalById' : IDL.Func([IDL.Text], [Hospital], ['query']),
  'getHospitals' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Hospital)],
      ['query'],
    ),
  'getHospitalsByPhlebotomist' : IDL.Func(
      [Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getPhlebotomistsByHospital' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Principal)],
      ['query'],
    ),
  'getSamplesByHospital' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SampleRecord)],
      ['query'],
    ),
  'getSamplesByMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SampleRecord)],
      ['query'],
    ),
  'getSettlementHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Settlement)],
      ['query'],
    ),
  'getSystemMode' : IDL.Func([], [SystemMode], ['query']),
  'getTasksByUser' : IDL.Func([IDL.Text], [IDL.Vec(AppTask)], ['query']),
  'getTest' : IDL.Func([IDL.Text], [IDL.Opt(TestOutput)], ['query']),
  'getTestByCode' : IDL.Func([IDL.Text], [IDL.Opt(TestOutput)], ['query']),
  'getUserByMobile' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markSettlement' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Variant({ 'Partial' : IDL.Null, 'Settled' : IDL.Null }),
        IDL.Opt(IDL.Text),
      ],
      [Settlement],
      [],
    ),
  'registerAppUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [AppUser],
      [],
    ),
  'removePhlebotomistFromHospital' : IDL.Func(
      [IDL.Text, Principal, IDL.Text],
      [HospitalPhlebotomistAssignment],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedTestUsers' : IDL.Func([], [IDL.Nat], []),
  'setSystemMode' : IDL.Func([SystemMode], [], []),
  'setTestStatus' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
      [],
    ),
  'updateHospital' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Hospital],
      [],
    ),
  'updateSampleStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
      [],
    ),
  'updateTest' : IDL.Func(
      [IDL.Text, TestInput],
      [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Hospital = IDL.Record({
    'id' : IDL.Text,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const TestInput = IDL.Record({
    'mrp' : IDL.Nat,
    'lab_cost' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'sampleType' : IDL.Text,
    'isActive' : IDL.Bool,
    'commission_amount' : IDL.Nat,
    'profit' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const TestOutput = IDL.Record({
    'id' : IDL.Text,
    'mrp' : IDL.Nat,
    'lab_cost' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'sampleType' : IDL.Text,
    'isActive' : IDL.Bool,
    'commission_amount' : IDL.Nat,
    'profit' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const TestError = IDL.Variant({
    'notFound' : IDL.Null,
    'duplicateCode' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const HospitalPhlebotomistAssignment = IDL.Record({
    'assignedAt' : IDL.Int,
    'assignedBy' : Principal,
    'isActive' : IDL.Bool,
    'hospitalId' : IDL.Text,
    'removedAt' : IDL.Opt(IDL.Int),
    'removalReason' : IDL.Opt(IDL.Text),
    'phlebotomist' : Principal,
  });
  const SampleTestItem = IDL.Record({
    'testCode' : IDL.Text,
    'testName' : IDL.Text,
    'price' : IDL.Nat,
    'testId' : IDL.Text,
  });
  const SampleInput = IDL.Record({
    'tests' : IDL.Vec(IDL.Opt(SampleTestItem)),
    'deliveryMethod' : IDL.Opt(IDL.Text),
    'hospitalId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'patientName' : IDL.Text,
    'paymentType' : IDL.Text,
    'createdByMobile' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AppTask = IDL.Record({
    'status' : IDL.Text,
    'patient_name' : IDL.Text,
    'hospital_id' : IDL.Text,
    'task_id' : IDL.Text,
    'created_at' : IDL.Int,
    'assigned_by' : IDL.Text,
    'assigned_to_mobile' : IDL.Text,
  });
  const AppUser = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'assignedHospitalId' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'mobile' : IDL.Text,
  });
  const SampleRecord = IDL.Record({
    'status' : IDL.Text,
    'tests' : IDL.Vec(SampleTestItem),
    'createdAt' : IDL.Int,
    'deliveryMethod' : IDL.Opt(IDL.Text),
    'hospitalId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'patientName' : IDL.Text,
    'paymentType' : IDL.Text,
    'createdByMobile' : IDL.Text,
    'phone' : IDL.Text,
    'sampleId' : IDL.Text,
  });
  const AppRole = IDL.Variant({
    'patient' : IDL.Null,
    'superAdmin' : IDL.Null,
    'labAdmin' : IDL.Null,
    'phlebotomist' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'area' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardMetrics = IDL.Record({
    'pendingReports' : IDL.Nat,
    'revenueToday' : IDL.Nat,
    'samplesToday' : IDL.Nat,
    'samplesTotal' : IDL.Nat,
    'collectionsToday' : IDL.Nat,
    'activeHospitals' : IDL.Nat,
  });
  const Settlement = IDL.Record({
    'settlementType' : IDL.Variant({
      'Partial' : IDL.Null,
      'Settled' : IDL.Null,
    }),
    'hospitalId' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const SystemMode = IDL.Variant({
    'production' : IDL.Null,
    'test' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHospital' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Hospital],
        [],
      ),
    'addTest' : IDL.Func(
        [TestInput],
        [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPhlebotomistToHospital' : IDL.Func(
        [IDL.Text, Principal],
        [HospitalPhlebotomistAssignment],
        [],
      ),
    'bulkAddTests' : IDL.Func([IDL.Vec(TestInput)], [IDL.Vec(TestOutput)], []),
    'createSample' : IDL.Func([SampleInput], [IDL.Text], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AppTask],
        [],
      ),
    'deleteAllData' : IDL.Func([], [], []),
    'deleteAllSampleData' : IDL.Func([], [IDL.Nat], []),
    'deleteAllTasks' : IDL.Func([], [IDL.Nat], []),
    'deleteTestUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'disableHospital' : IDL.Func([IDL.Text], [Hospital], []),
    'disableTest' : IDL.Func([IDL.Text], [TestOutput], []),
    'getAllAppUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
    'getAllSamples' : IDL.Func([], [IDL.Vec(SampleRecord)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(AppTask)], ['query']),
    'getAllTests' : IDL.Func([], [IDL.Vec(TestOutput)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getHospitalById' : IDL.Func([IDL.Text], [Hospital], ['query']),
    'getHospitals' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'getHospitalsByPhlebotomist' : IDL.Func(
        [Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPhlebotomistsByHospital' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Principal)],
        ['query'],
      ),
    'getSamplesByHospital' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SampleRecord)],
        ['query'],
      ),
    'getSamplesByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SampleRecord)],
        ['query'],
      ),
    'getSettlementHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Settlement)],
        ['query'],
      ),
    'getSystemMode' : IDL.Func([], [SystemMode], ['query']),
    'getTasksByUser' : IDL.Func([IDL.Text], [IDL.Vec(AppTask)], ['query']),
    'getTest' : IDL.Func([IDL.Text], [IDL.Opt(TestOutput)], ['query']),
    'getTestByCode' : IDL.Func([IDL.Text], [IDL.Opt(TestOutput)], ['query']),
    'getUserByMobile' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markSettlement' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Variant({ 'Partial' : IDL.Null, 'Settled' : IDL.Null }),
          IDL.Opt(IDL.Text),
        ],
        [Settlement],
        [],
      ),
    'registerAppUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [AppUser],
        [],
      ),
    'removePhlebotomistFromHospital' : IDL.Func(
        [IDL.Text, Principal, IDL.Text],
        [HospitalPhlebotomistAssignment],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedTestUsers' : IDL.Func([], [IDL.Nat], []),
    'setSystemMode' : IDL.Func([SystemMode], [], []),
    'setTestStatus' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
        [],
      ),
    'updateHospital' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Hospital],
        [],
      ),
    'updateSampleStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
        [],
      ),
    'updateTest' : IDL.Func(
        [IDL.Text, TestInput],
        [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };