/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'patient' : null } |
  { 'superAdmin' : null } |
  { 'labAdmin' : null } |
  { 'phlebotomist' : null };
export interface AppTask {
  'status' : string,
  'patient_name' : string,
  'hospital_id' : string,
  'task_id' : string,
  'created_at' : bigint,
  'assigned_by' : string,
  'assigned_to_mobile' : string,
}
export interface AppUser {
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'assignedHospitalId' : [] | [string],
  'isActive' : boolean,
  'mobile' : string,
}
export interface DashboardMetrics {
  'pendingReports' : bigint,
  'revenueToday' : bigint,
  'samplesToday' : bigint,
  'samplesTotal' : bigint,
  'collectionsToday' : bigint,
  'activeHospitals' : bigint,
}
export interface Hospital {
  'id' : string,
  'area' : string,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'address' : string,
  'contactNumber' : string,
}
export interface HospitalPhlebotomistAssignment {
  'assignedAt' : bigint,
  'assignedBy' : Principal,
  'isActive' : boolean,
  'hospitalId' : string,
  'removedAt' : [] | [bigint],
  'removalReason' : [] | [string],
  'phlebotomist' : Principal,
}
export type Principal = Principal;
export interface SampleInput {
  'tests' : Array<[] | [SampleTestItem]>,
  'deliveryMethod' : [] | [string],
  'hospitalId' : string,
  'totalAmount' : bigint,
  'patientName' : string,
  'paymentType' : string,
  'createdByMobile' : string,
  'phone' : string,
}
export interface SampleRecord {
  'status' : string,
  'tests' : Array<SampleTestItem>,
  'createdAt' : bigint,
  'deliveryMethod' : [] | [string],
  'hospitalId' : string,
  'totalAmount' : bigint,
  'patientName' : string,
  'paymentType' : string,
  'createdByMobile' : string,
  'phone' : string,
  'sampleId' : string,
}
export interface SampleTestItem {
  'testCode' : string,
  'testName' : string,
  'price' : bigint,
  'testId' : string,
}
export interface Settlement {
  'settlementType' : { 'Partial' : null } |
    { 'Settled' : null },
  'hospitalId' : string,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'amount' : bigint,
}
export type SystemMode = { 'production' : null } |
  { 'test' : null };
export type TestError = { 'notFound' : null } |
  { 'duplicateCode' : null };
export interface TestInput {
  'mrp' : bigint,
  'lab_cost' : bigint,
  'code' : string,
  'name' : string,
  'sampleType' : string,
  'isActive' : boolean,
  'commission_amount' : bigint,
  'profit' : bigint,
  'price' : bigint,
}
export interface TestOutput {
  'id' : string,
  'mrp' : bigint,
  'lab_cost' : bigint,
  'code' : string,
  'name' : string,
  'sampleType' : string,
  'isActive' : boolean,
  'commission_amount' : bigint,
  'profit' : bigint,
  'price' : bigint,
}
export interface UserProfile {
  'appRole' : AppRole,
  'area' : [] | [string],
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / HOSPITAL MANAGEMENT
   */
  'addHospital' : ActorMethod<
    [string, string, string, string, string],
    Hospital
  >,
  'addTest' : ActorMethod<
    [TestInput],
    { 'ok' : TestOutput } |
      { 'err' : TestError }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPhlebotomistToHospital' : ActorMethod<
    [string, Principal],
    HospitalPhlebotomistAssignment
  >,
  'bulkAddTests' : ActorMethod<[Array<TestInput>], Array<TestOutput>>,
  'createSample' : ActorMethod<[SampleInput], string>,
  'createTask' : ActorMethod<[string, string, string, string, string], AppTask>,
  'deleteAllData' : ActorMethod<[], undefined>,
  'deleteAllSampleData' : ActorMethod<[], bigint>,
  'deleteAllTasks' : ActorMethod<[], bigint>,
  'deleteTestUser' : ActorMethod<[string], boolean>,
  'disableHospital' : ActorMethod<[string], Hospital>,
  'disableTest' : ActorMethod<[string], TestOutput>,
  'getAllAppUsers' : ActorMethod<[], Array<AppUser>>,
  'getAllSamples' : ActorMethod<[], Array<SampleRecord>>,
  'getAllTasks' : ActorMethod<[], Array<AppTask>>,
  'getAllTests' : ActorMethod<[], Array<TestOutput>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getHospitalById' : ActorMethod<[string], Hospital>,
  'getHospitals' : ActorMethod<[[] | [string]], Array<Hospital>>,
  'getHospitalsByPhlebotomist' : ActorMethod<[Principal], Array<string>>,
  'getPhlebotomistsByHospital' : ActorMethod<[string], Array<Principal>>,
  'getSamplesByHospital' : ActorMethod<[string], Array<SampleRecord>>,
  'getSamplesByMobile' : ActorMethod<[string], Array<SampleRecord>>,
  'getSettlementHistory' : ActorMethod<[string], Array<Settlement>>,
  'getSystemMode' : ActorMethod<[], SystemMode>,
  'getTasksByUser' : ActorMethod<[string], Array<AppTask>>,
  'getTest' : ActorMethod<[string], [] | [TestOutput]>,
  'getTestByCode' : ActorMethod<[string], [] | [TestOutput]>,
  'getUserByMobile' : ActorMethod<[string], [] | [AppUser]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markSettlement' : ActorMethod<
    [
      string,
      bigint,
      { 'Partial' : null } |
        { 'Settled' : null },
      [] | [string],
    ],
    Settlement
  >,
  'registerAppUser' : ActorMethod<
    [string, string, string, [] | [string]],
    AppUser
  >,
  'removePhlebotomistFromHospital' : ActorMethod<
    [string, Principal, string],
    HospitalPhlebotomistAssignment
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedTestUsers' : ActorMethod<[], bigint>,
  'setSystemMode' : ActorMethod<[SystemMode], undefined>,
  'setTestStatus' : ActorMethod<
    [string, boolean],
    { 'ok' : TestOutput } |
      { 'err' : TestError }
  >,
  'updateHospital' : ActorMethod<
    [string, string, string, string, string, string],
    Hospital
  >,
  'updateSampleStatus' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'notFound' : null }
  >,
  'updateTest' : ActorMethod<
    [string, TestInput],
    { 'ok' : TestOutput } |
      { 'err' : TestError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];