/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Hospital = IDL.Record({
  'id' : IDL.Text,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const TestInput = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'sampleType' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Nat,
});
export const TestOutput = IDL.Record({
  'id' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'sampleType' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Nat,
});
export const TestError = IDL.Variant({
  'notFound' : IDL.Null,
  'duplicateCode' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HospitalPhlebotomistAssignment = IDL.Record({
  'assignedAt' : IDL.Int,
  'assignedBy' : IDL.Principal,
  'isActive' : IDL.Bool,
  'hospitalId' : IDL.Text,
  'removedAt' : IDL.Opt(IDL.Int),
  'removalReason' : IDL.Opt(IDL.Text),
  'phlebotomist' : IDL.Principal,
});
export const AppRole = IDL.Variant({
  'patient' : IDL.Null,
  'superAdmin' : IDL.Null,
  'labAdmin' : IDL.Null,
  'phlebotomist' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'area' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHospital' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Hospital],
      [],
    ),
  'addTest' : IDL.Func(
      [TestInput],
      [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPhlebotomistToHospital' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [HospitalPhlebotomistAssignment],
      [],
    ),
  'bulkAddTests' : IDL.Func([IDL.Vec(TestInput)], [IDL.Vec(TestOutput)], []),
  'disableHospital' : IDL.Func([IDL.Text], [Hospital], []),
  'disableTest' : IDL.Func([IDL.Text], [TestOutput], []),
  'getAllTests' : IDL.Func([], [IDL.Vec(TestOutput)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHospitalById' : IDL.Func([IDL.Text], [Hospital], ['query']),
  'getHospitals' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Hospital)],
      ['query'],
    ),
  'getHospitalsByPhlebotomist' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getPhlebotomistsByHospital' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getTest' : IDL.Func([IDL.Text], [IDL.Opt(TestOutput)], ['query']),
  'getTestByCode' : IDL.Func([IDL.Text], [IDL.Opt(TestOutput)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removePhlebotomistFromHospital' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text],
      [HospitalPhlebotomistAssignment],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTestStatus' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
      [],
    ),
  'updateHospital' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Hospital],
      [],
    ),
  'updateTest' : IDL.Func(
      [IDL.Text, TestInput],
      [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Hospital = IDL.Record({
    'id' : IDL.Text,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const TestInput = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'sampleType' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const TestOutput = IDL.Record({
    'id' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'sampleType' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const TestError = IDL.Variant({
    'notFound' : IDL.Null,
    'duplicateCode' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HospitalPhlebotomistAssignment = IDL.Record({
    'assignedAt' : IDL.Int,
    'assignedBy' : IDL.Principal,
    'isActive' : IDL.Bool,
    'hospitalId' : IDL.Text,
    'removedAt' : IDL.Opt(IDL.Int),
    'removalReason' : IDL.Opt(IDL.Text),
    'phlebotomist' : IDL.Principal,
  });
  const AppRole = IDL.Variant({
    'patient' : IDL.Null,
    'superAdmin' : IDL.Null,
    'labAdmin' : IDL.Null,
    'phlebotomist' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'area' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHospital' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Hospital],
        [],
      ),
    'addTest' : IDL.Func(
        [TestInput],
        [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPhlebotomistToHospital' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [HospitalPhlebotomistAssignment],
        [],
      ),
    'bulkAddTests' : IDL.Func([IDL.Vec(TestInput)], [IDL.Vec(TestOutput)], []),
    'disableHospital' : IDL.Func([IDL.Text], [Hospital], []),
    'disableTest' : IDL.Func([IDL.Text], [TestOutput], []),
    'getAllTests' : IDL.Func([], [IDL.Vec(TestOutput)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHospitalById' : IDL.Func([IDL.Text], [Hospital], ['query']),
    'getHospitals' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'getHospitalsByPhlebotomist' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPhlebotomistsByHospital' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getTest' : IDL.Func([IDL.Text], [IDL.Opt(TestOutput)], ['query']),
    'getTestByCode' : IDL.Func([IDL.Text], [IDL.Opt(TestOutput)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removePhlebotomistFromHospital' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [HospitalPhlebotomistAssignment],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTestStatus' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
        [],
      ),
    'updateHospital' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Hospital],
        [],
      ),
    'updateTest' : IDL.Func(
        [IDL.Text, TestInput],
        [IDL.Variant({ 'ok' : TestOutput, 'err' : TestError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };