/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Test = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const Attendance = IDL.Record({
  'status' : IDL.Text,
  'totalWorkingMinutes' : IDL.Opt(IDL.Int),
  'checkInSelfieUrl' : IDL.Text,
  'checkInLong' : IDL.Float64,
  'checkInTime' : IDL.Int,
  'phlebotomistId' : IDL.Text,
  'hospitalId' : IDL.Text,
  'checkOutLong' : IDL.Opt(IDL.Float64),
  'checkOutTime' : IDL.Opt(IDL.Int),
  'checkInLat' : IDL.Float64,
  'checkOutLat' : IDL.Opt(IDL.Float64),
});
export const AuditLog = IDL.Record({
  'actionType' : IDL.Text,
  'actorId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'targetDocument' : IDL.Text,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'canceled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'patient' : IDL.Principal,
  'tests' : IDL.Vec(Test),
  'slot' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const HomeCollectionRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'assigned' : IDL.Null,
    'requested' : IDL.Null,
    'canceled' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'latitude' : IDL.Opt(IDL.Float64),
  'patient' : IDL.Principal,
  'tests' : IDL.Vec(Test),
  'slot' : IDL.Text,
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'assignedPhlebotomist' : IDL.Opt(IDL.Principal),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Incident = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'photo' : IDL.Opt(ExternalBlob),
  'reporter' : IDL.Principal,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'patient' : IDL.Principal,
  'bookingId' : IDL.Text,
  'file' : ExternalBlob,
  'timestamp' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const BPReading = IDL.Record({
  'systolic' : IDL.Nat,
  'timestamp' : IDL.Int,
  'diastolic' : IDL.Nat,
  'pulse' : IDL.Nat,
});
export const AppRole = IDL.Variant({
  'patient' : IDL.Null,
  'superAdmin' : IDL.Null,
  'labAdmin' : IDL.Null,
  'phlebotomist' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const HospitalSample = IDL.Record({
  'mrp' : IDL.Float64,
  'status' : IDL.Text,
  'finalAmount' : IDL.Float64,
  'createdAt' : IDL.Int,
  'phlebotomistId' : IDL.Text,
  'hospitalId' : IDL.Text,
  'patientName' : IDL.Text,
  'discount' : IDL.Float64,
  'paymentMode' : IDL.Text,
  'phone' : IDL.Text,
  'pendingAmount' : IDL.Float64,
  'amountReceived' : IDL.Float64,
  'testId' : IDL.Text,
});
export const RBSTest = IDL.Record({
  'glucoseLevel' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const SecurityLog = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'userId' : IDL.Text,
  'longitude' : IDL.Opt(IDL.Float64),
  'deviceId' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventType' : IDL.Text,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPhlebotomist' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'bindDevice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'createBooking' : IDL.Func([IDL.Text, IDL.Vec(Test), IDL.Text], [], []),
  'createHomeCollectionRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Vec(Test),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createHospitalSample' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createSecurityLog' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createTest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteTest' : IDL.Func([IDL.Text], [], []),
  'endShift' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'getActiveShift' : IDL.Func([IDL.Text], [IDL.Opt(Attendance)], ['query']),
  'getAllActiveShifts' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getAllAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllHomeCollectionRequests' : IDL.Func(
      [],
      [IDL.Vec(HomeCollectionRequest)],
      ['query'],
    ),
  'getAllIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getAllTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getAttendanceByPhlebotomist' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getBPReadings' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(BPReading)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHospitalSamplesByHospital' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HospitalSample)],
      ['query'],
    ),
  'getHospitalSamplesByPhlebotomist' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HospitalSample)],
      ['query'],
    ),
  'getHospitalSamplesByPhone' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalReceived' : IDL.Float64,
          'count' : IDL.Nat,
          'samples' : IDL.Vec(HospitalSample),
          'totalAmount' : IDL.Float64,
          'totalPending' : IDL.Float64,
          'totalDiscount' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyHomeCollectionRequests' : IDL.Func(
      [],
      [IDL.Vec(HomeCollectionRequest)],
      ['query'],
    ),
  'getMyIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'getMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getRBSReadings' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(RBSTest)],
      ['query'],
    ),
  'getSecurityLogs' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SecurityLog)],
      ['query'],
    ),
  'getTest' : IDL.Func([IDL.Text], [Test], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordBPReading' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'recordRBSReading' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
  'resetDeviceBinding' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startShift' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'submitIncident' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'low' : IDL.Null,
          'high' : IDL.Null,
          'medium' : IDL.Null,
        }),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateBookingStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'canceled' : IDL.Null,
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateHomeCollectionStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'assigned' : IDL.Null,
          'requested' : IDL.Null,
          'canceled' : IDL.Null,
          'completed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateHospitalSampleBilling' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'uploadReport' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Test = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Attendance = IDL.Record({
    'status' : IDL.Text,
    'totalWorkingMinutes' : IDL.Opt(IDL.Int),
    'checkInSelfieUrl' : IDL.Text,
    'checkInLong' : IDL.Float64,
    'checkInTime' : IDL.Int,
    'phlebotomistId' : IDL.Text,
    'hospitalId' : IDL.Text,
    'checkOutLong' : IDL.Opt(IDL.Float64),
    'checkOutTime' : IDL.Opt(IDL.Int),
    'checkInLat' : IDL.Float64,
    'checkOutLat' : IDL.Opt(IDL.Float64),
  });
  const AuditLog = IDL.Record({
    'actionType' : IDL.Text,
    'actorId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'targetDocument' : IDL.Text,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'canceled' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'patient' : IDL.Principal,
    'tests' : IDL.Vec(Test),
    'slot' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const HomeCollectionRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'assigned' : IDL.Null,
      'requested' : IDL.Null,
      'canceled' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'latitude' : IDL.Opt(IDL.Float64),
    'patient' : IDL.Principal,
    'tests' : IDL.Vec(Test),
    'slot' : IDL.Text,
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'assignedPhlebotomist' : IDL.Opt(IDL.Principal),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Incident = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'photo' : IDL.Opt(ExternalBlob),
    'reporter' : IDL.Principal,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'patient' : IDL.Principal,
    'bookingId' : IDL.Text,
    'file' : ExternalBlob,
    'timestamp' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const BPReading = IDL.Record({
    'systolic' : IDL.Nat,
    'timestamp' : IDL.Int,
    'diastolic' : IDL.Nat,
    'pulse' : IDL.Nat,
  });
  const AppRole = IDL.Variant({
    'patient' : IDL.Null,
    'superAdmin' : IDL.Null,
    'labAdmin' : IDL.Null,
    'phlebotomist' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const HospitalSample = IDL.Record({
    'mrp' : IDL.Float64,
    'status' : IDL.Text,
    'finalAmount' : IDL.Float64,
    'createdAt' : IDL.Int,
    'phlebotomistId' : IDL.Text,
    'hospitalId' : IDL.Text,
    'patientName' : IDL.Text,
    'discount' : IDL.Float64,
    'paymentMode' : IDL.Text,
    'phone' : IDL.Text,
    'pendingAmount' : IDL.Float64,
    'amountReceived' : IDL.Float64,
    'testId' : IDL.Text,
  });
  const RBSTest = IDL.Record({
    'glucoseLevel' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const SecurityLog = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'userId' : IDL.Text,
    'longitude' : IDL.Opt(IDL.Float64),
    'deviceId' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventType' : IDL.Text,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPhlebotomist' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'bindDevice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'createBooking' : IDL.Func([IDL.Text, IDL.Vec(Test), IDL.Text], [], []),
    'createHomeCollectionRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Vec(Test),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createHospitalSample' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createSecurityLog' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createTest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'deleteTest' : IDL.Func([IDL.Text], [], []),
    'endShift' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'getActiveShift' : IDL.Func([IDL.Text], [IDL.Opt(Attendance)], ['query']),
    'getAllActiveShifts' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getAllAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllHomeCollectionRequests' : IDL.Func(
        [],
        [IDL.Vec(HomeCollectionRequest)],
        ['query'],
      ),
    'getAllIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getAllTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getAttendanceByPhlebotomist' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getBPReadings' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(BPReading)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHospitalSamplesByHospital' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HospitalSample)],
        ['query'],
      ),
    'getHospitalSamplesByPhlebotomist' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HospitalSample)],
        ['query'],
      ),
    'getHospitalSamplesByPhone' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalReceived' : IDL.Float64,
            'count' : IDL.Nat,
            'samples' : IDL.Vec(HospitalSample),
            'totalAmount' : IDL.Float64,
            'totalPending' : IDL.Float64,
            'totalDiscount' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyHomeCollectionRequests' : IDL.Func(
        [],
        [IDL.Vec(HomeCollectionRequest)],
        ['query'],
      ),
    'getMyIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'getMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getRBSReadings' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(RBSTest)],
        ['query'],
      ),
    'getSecurityLogs' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SecurityLog)],
        ['query'],
      ),
    'getTest' : IDL.Func([IDL.Text], [Test], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordBPReading' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'recordRBSReading' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
    'resetDeviceBinding' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startShift' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'submitIncident' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'low' : IDL.Null,
            'high' : IDL.Null,
            'medium' : IDL.Null,
          }),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateBookingStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'canceled' : IDL.Null,
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateHomeCollectionStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'assigned' : IDL.Null,
            'requested' : IDL.Null,
            'canceled' : IDL.Null,
            'completed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateHospitalSampleBilling' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadReport' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };