/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'patient' : null } |
  { 'superAdmin' : null } |
  { 'labAdmin' : null } |
  { 'phlebotomist' : null };
export interface Attendance {
  'status' : string,
  'totalWorkingMinutes' : [] | [bigint],
  'checkInSelfieUrl' : string,
  'checkInLong' : number,
  'checkInTime' : bigint,
  'phlebotomistId' : string,
  'hospitalId' : string,
  'checkOutLong' : [] | [number],
  'checkOutTime' : [] | [bigint],
  'checkInLat' : number,
  'checkOutLat' : [] | [number],
}
export interface AuditLog {
  'actionType' : string,
  'actorId' : Principal,
  'timestamp' : bigint,
  'targetDocument' : string,
}
export interface BPReading {
  'systolic' : bigint,
  'timestamp' : bigint,
  'diastolic' : bigint,
  'pulse' : bigint,
}
export interface Booking {
  'id' : string,
  'status' : { 'canceled' : null } |
    { 'pending' : null } |
    { 'completed' : null } |
    { 'confirmed' : null },
  'patient' : Principal,
  'tests' : Array<Test>,
  'slot' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface HomeCollectionRequest {
  'id' : string,
  'status' : { 'assigned' : null } |
    { 'requested' : null } |
    { 'canceled' : null } |
    { 'completed' : null },
  'latitude' : [] | [number],
  'patient' : Principal,
  'tests' : Array<Test>,
  'slot' : string,
  'longitude' : [] | [number],
  'address' : string,
  'timestamp' : bigint,
  'assignedPhlebotomist' : [] | [Principal],
}
export interface HospitalSample {
  'mrp' : number,
  'status' : string,
  'finalAmount' : number,
  'createdAt' : bigint,
  'phlebotomistId' : string,
  'hospitalId' : string,
  'patientName' : string,
  'discount' : number,
  'paymentMode' : string,
  'phone' : string,
  'pendingAmount' : number,
  'amountReceived' : number,
  'testId' : string,
}
export interface Incident {
  'id' : string,
  'description' : string,
  'timestamp' : bigint,
  'severity' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
  'photo' : [] | [ExternalBlob],
  'reporter' : Principal,
}
export interface RBSTest { 'glucoseLevel' : bigint, 'timestamp' : bigint }
export interface Report {
  'id' : string,
  'patient' : Principal,
  'bookingId' : string,
  'file' : ExternalBlob,
  'timestamp' : bigint,
  'uploadedBy' : Principal,
}
export interface SecurityLog {
  'latitude' : [] | [number],
  'userId' : string,
  'longitude' : [] | [number],
  'deviceId' : string,
  'timestamp' : bigint,
  'eventType' : string,
  'reason' : string,
}
export interface Test {
  'id' : string,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface UserProfile {
  'appRole' : AppRole,
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Admin-only: assign a phlebotomist to a home collection request
   */
  'assignPhlebotomist' : ActorMethod<[string, Principal], undefined>,
  /**
   * / Authenticated users only: bind a device on first login.
   * / If a binding already exists for a different deviceId, returns an error.
   * / The caller must be the user identified by userId (ownership check).
   */
  'bindDevice' : ActorMethod<[string, string, string, string], undefined>,
  /**
   * / Registered users (patients) can create bookings
   */
  'createBooking' : ActorMethod<[string, Array<Test>, string], undefined>,
  /**
   * / Registered users (patients) can request home collection
   */
  'createHomeCollectionRequest' : ActorMethod<
    [string, string, [] | [number], [] | [number], Array<Test>, string],
    undefined
  >,
  /**
   * / Phlebotomist-only (registered user): create a hospital sample with status SAMPLE_COLLECTED
   */
  'createHospitalSample' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      string,
    ],
    undefined
  >,
  /**
   * / Authenticated users (phlebotomists) or system: write a security log entry.
   * / No role restriction beyond being an authenticated user — guests are blocked.
   */
  'createSecurityLog' : ActorMethod<
    [string, string, string, [] | [number], [] | [number], string],
    undefined
  >,
  /**
   * / Authenticated users only: create (or replace) a session token.
   * / On login, a new ACTIVE session is written and any previous session for the
   * / same userId is implicitly superseded (the map entry is overwritten).
   * / The caller must be the user identified by userId (ownership check).
   */
  'createSession' : ActorMethod<[string, string], undefined>,
  /**
   * / Admin-only: create a diagnostic test entry
   */
  'createTest' : ActorMethod<[string, string, string, bigint], undefined>,
  /**
   * / Admin-only: remove a diagnostic test
   */
  'deleteTest' : ActorMethod<[string], undefined>,
  /**
   * / Phlebotomist-only (registered user): end their own active shift.
   * / The caller must be the phlebotomist identified by phlebotomistId (ownership check).
   */
  'endShift' : ActorMethod<[string, string, number, number], undefined>,
  /**
   * / Phlebotomist-only (registered user): get their own active shift.
   * / The caller must be the phlebotomist identified by phlebotomistId (ownership check).
   */
  'getActiveShift' : ActorMethod<[string], [] | [Attendance]>,
  /**
   * / Admin-only: get all currently active shifts
   */
  'getAllActiveShifts' : ActorMethod<[], Array<Attendance>>,
  /**
   * / Admin-only: view all audit logs
   */
  'getAllAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  /**
   * / Admin-only: view all bookings
   */
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  /**
   * / Admin-only: view all home collection requests
   */
  'getAllHomeCollectionRequests' : ActorMethod<
    [],
    Array<HomeCollectionRequest>
  >,
  /**
   * / Admin-only: view all incidents
   */
  'getAllIncidents' : ActorMethod<[], Array<Incident>>,
  /**
   * / Admin-only: view all reports
   */
  'getAllReports' : ActorMethod<[], Array<Report>>,
  /**
   * / Public: any caller (including guests) can list all available tests
   */
  'getAllTests' : ActorMethod<[], Array<Test>>,
  /**
   * / Admin-only: get all attendance records for a specific phlebotomist
   */
  'getAttendanceByPhlebotomist' : ActorMethod<[string], Array<Attendance>>,
  /**
   * / Registered users can view BP readings for themselves; admins can view any
   */
  'getBPReadings' : ActorMethod<[Principal, string], Array<BPReading>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Admin-only: get hospital samples filtered by hospitalId
   */
  'getHospitalSamplesByHospital' : ActorMethod<[string], Array<HospitalSample>>,
  /**
   * / Admin-only: get hospital samples filtered by phlebotomistId
   */
  'getHospitalSamplesByPhlebotomist' : ActorMethod<
    [string],
    Array<HospitalSample>
  >,
  /**
   * / Patient (registered user) or admin: get hospital samples filtered by phone number.
   * / This supports the patient-linked view. Any authenticated user may query by phone
   * / (patients look up their own records; admins may look up any).
   */
  'getHospitalSamplesByPhone' : ActorMethod<
    [string],
    {
      'totalReceived' : number,
      'count' : bigint,
      'samples' : Array<HospitalSample>,
      'totalAmount' : number,
      'totalPending' : number,
      'totalDiscount' : number,
    }
  >,
  /**
   * / Registered users can view their own bookings
   */
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  /**
   * / Registered users can view their own home collection requests
   */
  'getMyHomeCollectionRequests' : ActorMethod<[], Array<HomeCollectionRequest>>,
  /**
   * / Registered users can view incidents they reported
   */
  'getMyIncidents' : ActorMethod<[], Array<Incident>>,
  /**
   * / Registered users can view their own reports
   */
  'getMyReports' : ActorMethod<[], Array<Report>>,
  /**
   * / Registered users can view RBS readings for themselves; admins can view any
   */
  'getRBSReadings' : ActorMethod<[Principal, string], Array<RBSTest>>,
  /**
   * / Admin/super-admin only: retrieve security logs, optionally filtered by userId and eventType.
   * / Pass empty strings to skip a filter.
   */
  'getSecurityLogs' : ActorMethod<[string, string], Array<SecurityLog>>,
  /**
   * / Public: any caller (including guests) can browse available tests
   */
  'getTest' : ActorMethod<[string], Test>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Registered users (phlebotomists/lab staff) can record BP readings for a patient
   */
  'recordBPReading' : ActorMethod<
    [Principal, string, bigint, bigint, bigint],
    undefined
  >,
  /**
   * / Registered users (phlebotomists/lab staff) can record RBS readings for a patient
   */
  'recordRBSReading' : ActorMethod<[Principal, string, bigint], undefined>,
  /**
   * / Admin-only: remove the device binding for a given userId
   */
  'resetDeviceBinding' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Phlebotomist-only (registered user): start a shift.
   * / The caller must be the phlebotomist identified by phlebotomistId (ownership check).
   * / Validates: no existing ACTIVE shift for this phlebotomist.
   */
  'startShift' : ActorMethod<
    [string, string, number, number, string],
    undefined
  >,
  /**
   * / Registered users (any staff) can submit incidents
   */
  'submitIncident' : ActorMethod<
    [
      string,
      string,
      { 'low' : null } |
        { 'high' : null } |
        { 'medium' : null },
      [] | [ExternalBlob],
    ],
    undefined
  >,
  /**
   * / Admin-only: update booking status
   */
  'updateBookingStatus' : ActorMethod<
    [
      string,
      { 'canceled' : null } |
        { 'pending' : null } |
        { 'completed' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  /**
   * / Registered users can update the status of a home collection request they are assigned to or own
   */
  'updateHomeCollectionStatus' : ActorMethod<
    [
      string,
      { 'assigned' : null } |
        { 'requested' : null } |
        { 'canceled' : null } |
        { 'completed' : null },
    ],
    undefined
  >,
  /**
   * / Admin-only: update billing fields of a hospital sample
   */
  'updateHospitalSampleBilling' : ActorMethod<
    [string, number, number, number, number, string],
    undefined
  >,
  /**
   * / Admin-only: upload a PDF report linked to a booking
   */
  'uploadReport' : ActorMethod<
    [string, Principal, string, ExternalBlob],
    undefined
  >,
  /**
   * / Authenticated users only: validate that the presented session token matches
   * / the current ACTIVE session for the given userId.
   * / Returns true if valid, false if the session has been superseded.
   * / The caller must be the user identified by userId (ownership check).
   */
  'validateSession' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];