/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Settlement {
    settlementType: Variant_Partial_Settled;
    hospitalId: string;
    notes?: string;
    timestamp: bigint;
    amount: bigint;
}
export interface SampleTestItem {
    testCode: string;
    testName: string;
    price: bigint;
    testId: string;
}
export type Principal = Principal;
export interface TestOutput {
    id: string;
    mrp: bigint;
    lab_cost: bigint;
    code: string;
    name: string;
    sampleType: string;
    isActive: boolean;
    commission_amount: bigint;
    profit: bigint;
    price: bigint;
}
export interface AppTask {
    status: string;
    patient_name: string;
    hospital_id: string;
    task_id: string;
    created_at: bigint;
    assigned_by: string;
    assigned_to_mobile: string;
}
export interface HospitalPhlebotomistAssignment {
    assignedAt: bigint;
    assignedBy: Principal;
    isActive: boolean;
    hospitalId: string;
    removedAt?: bigint;
    removalReason?: string;
    phlebotomist: Principal;
}
export interface AppUser {
    name: string;
    createdAt: bigint;
    role: string;
    assignedHospitalId?: string;
    isActive: boolean;
    mobile: string;
}
export interface TestInput {
    mrp: bigint;
    lab_cost: bigint;
    code: string;
    name: string;
    sampleType: string;
    isActive: boolean;
    commission_amount: bigint;
    profit: bigint;
    price: bigint;
}
export interface SampleInput {
    tests: Array<SampleTestItem | null>;
    deliveryMethod?: string;
    hospitalId: string;
    totalAmount: bigint;
    patientName: string;
    paymentType: string;
    createdByMobile: string;
    phone: string;
}
export interface Hospital {
    id: string;
    area: string;
    city: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    address: string;
    contactNumber: string;
}
export interface DashboardMetrics {
    pendingReports: bigint;
    revenueToday: bigint;
    samplesToday: bigint;
    samplesTotal: bigint;
    collectionsToday: bigint;
    activeHospitals: bigint;
}
export interface UserProfile {
    appRole: AppRole;
    area?: string;
    name: string;
    phone: string;
}
export interface SampleRecord {
    status: string;
    tests: Array<SampleTestItem>;
    createdAt: bigint;
    deliveryMethod?: string;
    hospitalId: string;
    totalAmount: bigint;
    patientName: string;
    paymentType: string;
    createdByMobile: string;
    phone: string;
    sampleId: string;
}
export enum AppRole {
    patient = "patient",
    superAdmin = "superAdmin",
    labAdmin = "labAdmin",
    phlebotomist = "phlebotomist"
}
export enum SystemMode {
    production = "production",
    test = "test"
}
export enum TestError {
    notFound = "notFound",
    duplicateCode = "duplicateCode"
}
export enum Variant_Partial_Settled {
    Partial_ = "Partial",
    Settled = "Settled"
}
export enum Variant_ok_notFound {
    ok = "ok",
    notFound = "notFound"
}
export interface backendInterface {
    /**
     * / HOSPITAL MANAGEMENT
     */
    addHospital(name: string, city: string, address: string, area: string, contactNumber: string): Promise<Hospital>;
    addTest(input: TestInput): Promise<{
        __kind__: "ok";
        ok: TestOutput;
    } | {
        __kind__: "err";
        err: TestError;
    }>;
    assignPhlebotomistToHospital(hospitalId: string, phlebotomist: Principal): Promise<HospitalPhlebotomistAssignment>;
    bulkAddTests(testInputs: Array<TestInput>): Promise<Array<TestOutput>>;
    claimSuperAdmin(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createSample(input: SampleInput): Promise<string>;
    createTask(assigned_to_mobile: string, assigned_by: string, hospital_id: string, patient_name: string, status: string): Promise<AppTask>;
    deleteAllData(): Promise<void>;
    deleteAllSampleData(): Promise<bigint>;
    deleteAllTasks(): Promise<bigint>;
    deleteTestUser(mobile: string): Promise<boolean>;
    disableHospital(id: string): Promise<Hospital>;
    disableTest(code: string): Promise<TestOutput>;
    getAllAppUsers(): Promise<Array<AppUser>>;
    getAllSamples(): Promise<Array<SampleRecord>>;
    getAllTasks(): Promise<Array<AppTask>>;
    getAllTests(): Promise<Array<TestOutput>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getDashboardMetrics(): Promise<DashboardMetrics>;
    getHospitalById(id: string): Promise<Hospital>;
    getHospitals(search: string | null): Promise<Array<Hospital>>;
    getHospitalsByPhlebotomist(phlebotomist: Principal): Promise<Array<string>>;
    getPhlebotomistsByHospital(hospitalId: string): Promise<Array<Principal>>;
    getSamplesByHospital(hospitalId: string): Promise<Array<SampleRecord>>;
    getSamplesByMobile(mobile: string): Promise<Array<SampleRecord>>;
    getSettlementHistory(hospitalId: string): Promise<Array<Settlement>>;
    getSystemMode(): Promise<SystemMode>;
    getTasksByUser(mobile: string): Promise<Array<AppTask>>;
    getTest(code: string): Promise<TestOutput | null>;
    getTestByCode(testCode: string): Promise<TestOutput | null>;
    getUserByMobile(mobile: string): Promise<AppUser | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    markSettlement(hospitalId: string, amount: bigint, settlementType: Variant_Partial_Settled, notes: string | null): Promise<Settlement>;
    registerAppUser(mobile: string, name: string, role: string, assignedHospitalId: string | null): Promise<AppUser>;
    removePhlebotomistFromHospital(hospitalId: string, phlebotomist: Principal, removalReason: string): Promise<HospitalPhlebotomistAssignment>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedTestUsers(): Promise<bigint>;
    setSystemMode(mode: SystemMode): Promise<void>;
    setTestStatus(testId: string, isActive: boolean): Promise<{
        __kind__: "ok";
        ok: TestOutput;
    } | {
        __kind__: "err";
        err: TestError;
    }>;
    updateHospital(id: string, name: string, city: string, address: string, area: string, contactNumber: string): Promise<Hospital>;
    updateSampleStatus(sampleId: string, status: string): Promise<Variant_ok_notFound>;
    updateTest(code: string, input: TestInput): Promise<{
        __kind__: "ok";
        ok: TestOutput;
    } | {
        __kind__: "err";
        err: TestError;
    }>;
}
import type { AppRole as _AppRole, AppUser as _AppUser, HospitalPhlebotomistAssignment as _HospitalPhlebotomistAssignment, Principal as _Principal, SampleInput as _SampleInput, SampleRecord as _SampleRecord, SampleTestItem as _SampleTestItem, Settlement as _Settlement, SystemMode as _SystemMode, TestError as _TestError, TestOutput as _TestOutput, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addHospital(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.addHospital(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHospital(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addTest(arg0: TestInput): Promise<{
        __kind__: "ok";
        ok: TestOutput;
    } | {
        __kind__: "err";
        err: TestError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addTest(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTest(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignPhlebotomistToHospital(arg0: string, arg1: Principal): Promise<HospitalPhlebotomistAssignment> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPhlebotomistToHospital(arg0, arg1);
                return from_candid_HospitalPhlebotomistAssignment_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPhlebotomistToHospital(arg0, arg1);
            return from_candid_HospitalPhlebotomistAssignment_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkAddTests(arg0: Array<TestInput>): Promise<Array<TestOutput>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddTests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddTests(arg0);
            return result;
        }
    }
    async claimSuperAdmin(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.claimSuperAdmin();
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimSuperAdmin();
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSample(arg0: SampleInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSample(to_candid_SampleInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSample(to_candid_SampleInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<AppTask> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllData();
            return result;
        }
    }
    async deleteAllSampleData(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllSampleData();
            return result;
        }
    }
    async deleteAllTasks(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllTasks();
            return result;
        }
    }
    async deleteTestUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestUser(arg0);
            return result;
        }
    }
    async disableHospital(arg0: string): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.disableHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableHospital(arg0);
            return result;
        }
    }
    async disableTest(arg0: string): Promise<TestOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.disableTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableTest(arg0);
            return result;
        }
    }
    async getAllAppUsers(): Promise<Array<AppUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppUsers();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppUsers();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSamples(): Promise<Array<SampleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSamples();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSamples();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<AppTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return result;
        }
    }
    async getAllTests(): Promise<Array<TestOutput>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTests();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardMetrics(): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return result;
        }
    }
    async getHospitalById(arg0: string): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalById(arg0);
            return result;
        }
    }
    async getHospitals(arg0: string | null): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitals(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitals(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getHospitalsByPhlebotomist(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalsByPhlebotomist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalsByPhlebotomist(arg0);
            return result;
        }
    }
    async getPhlebotomistsByHospital(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhlebotomistsByHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhlebotomistsByHospital(arg0);
            return result;
        }
    }
    async getSamplesByHospital(arg0: string): Promise<Array<SampleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSamplesByHospital(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSamplesByHospital(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSamplesByMobile(arg0: string): Promise<Array<SampleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSamplesByMobile(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSamplesByMobile(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettlementHistory(arg0: string): Promise<Array<Settlement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettlementHistory(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettlementHistory(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemMode(): Promise<SystemMode> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemMode();
                return from_candid_SystemMode_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemMode();
            return from_candid_SystemMode_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByUser(arg0: string): Promise<Array<AppTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByUser(arg0);
            return result;
        }
    }
    async getTest(arg0: string): Promise<TestOutput | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTest(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTest(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestByCode(arg0: string): Promise<TestOutput | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestByCode(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestByCode(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByMobile(arg0: string): Promise<AppUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByMobile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByMobile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async markSettlement(arg0: string, arg1: bigint, arg2: Variant_Partial_Settled, arg3: string | null): Promise<Settlement> {
        if (this.processError) {
            try {
                const result = await this.actor.markSettlement(arg0, arg1, to_candid_variant_n33(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Settlement_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSettlement(arg0, arg1, to_candid_variant_n33(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Settlement_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAppUser(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<AppUser> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAppUser(arg0, arg1, arg2, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3));
                return from_candid_AppUser_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAppUser(arg0, arg1, arg2, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3));
            return from_candid_AppUser_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async removePhlebotomistFromHospital(arg0: string, arg1: Principal, arg2: string): Promise<HospitalPhlebotomistAssignment> {
        if (this.processError) {
            try {
                const result = await this.actor.removePhlebotomistFromHospital(arg0, arg1, arg2);
                return from_candid_HospitalPhlebotomistAssignment_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePhlebotomistFromHospital(arg0, arg1, arg2);
            return from_candid_HospitalPhlebotomistAssignment_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedTestUsers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.seedTestUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedTestUsers();
            return result;
        }
    }
    async setSystemMode(arg0: SystemMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSystemMode(to_candid_SystemMode_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSystemMode(to_candid_SystemMode_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setTestStatus(arg0: string, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: TestOutput;
    } | {
        __kind__: "err";
        err: TestError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setTestStatus(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTestStatus(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHospital(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHospital(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHospital(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateSampleStatus(arg0: string, arg1: string): Promise<Variant_ok_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSampleStatus(arg0, arg1);
                return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSampleStatus(arg0, arg1);
            return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTest(arg0: string, arg1: TestInput): Promise<{
        __kind__: "ok";
        ok: TestOutput;
    } | {
        __kind__: "err";
        err: TestError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTest(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTest(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_AppUser_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUser): AppUser {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_HospitalPhlebotomistAssignment_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HospitalPhlebotomistAssignment): HospitalPhlebotomistAssignment {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SampleRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleRecord): SampleRecord {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Settlement_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Settlement): Settlement {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SystemMode_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemMode): SystemMode {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TestError_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestError): TestError {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestOutput]): TestOutput | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppUser]): AppUser | null {
    return value.length === 0 ? null : from_candid_AppUser_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: bigint;
    role: string;
    assignedHospitalId: [] | [string];
    isActive: boolean;
    mobile: string;
}): {
    name: string;
    createdAt: bigint;
    role: string;
    assignedHospitalId?: string;
    isActive: boolean;
    mobile: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: value.role,
        assignedHospitalId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedHospitalId)),
        isActive: value.isActive,
        mobile: value.mobile
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    tests: Array<_SampleTestItem>;
    createdAt: bigint;
    deliveryMethod: [] | [string];
    hospitalId: string;
    totalAmount: bigint;
    patientName: string;
    paymentType: string;
    createdByMobile: string;
    phone: string;
    sampleId: string;
}): {
    status: string;
    tests: Array<SampleTestItem>;
    createdAt: bigint;
    deliveryMethod?: string;
    hospitalId: string;
    totalAmount: bigint;
    patientName: string;
    paymentType: string;
    createdByMobile: string;
    phone: string;
    sampleId: string;
} {
    return {
        status: value.status,
        tests: value.tests,
        createdAt: value.createdAt,
        deliveryMethod: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.deliveryMethod)),
        hospitalId: value.hospitalId,
        totalAmount: value.totalAmount,
        patientName: value.patientName,
        paymentType: value.paymentType,
        createdByMobile: value.createdByMobile,
        phone: value.phone,
        sampleId: value.sampleId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: _AppRole;
    area: [] | [string];
    name: string;
    phone: string;
}): {
    appRole: AppRole;
    area?: string;
    name: string;
    phone: string;
} {
    return {
        appRole: from_candid_AppRole_n22(_uploadFile, _downloadFile, value.appRole),
        area: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.area)),
        name: value.name,
        phone: value.phone
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    settlementType: {
        Partial: null;
    } | {
        Settled: null;
    };
    hospitalId: string;
    notes: [] | [string];
    timestamp: bigint;
    amount: bigint;
}): {
    settlementType: Variant_Partial_Settled;
    hospitalId: string;
    notes?: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        settlementType: from_candid_variant_n28(_uploadFile, _downloadFile, value.settlementType),
        hospitalId: value.hospitalId,
        notes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedAt: bigint;
    assignedBy: _Principal;
    isActive: boolean;
    hospitalId: string;
    removedAt: [] | [bigint];
    removalReason: [] | [string];
    phlebotomist: _Principal;
}): {
    assignedAt: bigint;
    assignedBy: Principal;
    isActive: boolean;
    hospitalId: string;
    removedAt?: bigint;
    removalReason?: string;
    phlebotomist: Principal;
} {
    return {
        assignedAt: value.assignedAt,
        assignedBy: value.assignedBy,
        isActive: value.isActive,
        hospitalId: value.hospitalId,
        removedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.removedAt)),
        removalReason: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.removalReason)),
        phlebotomist: value.phlebotomist
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TestOutput;
} | {
    err: _TestError;
}): {
    __kind__: "ok";
    ok: TestOutput;
} | {
    __kind__: "err";
    err: TestError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_TestError_n2(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    superAdmin: null;
} | {
    labAdmin: null;
} | {
    phlebotomist: null;
}): AppRole {
    return "patient" in value ? AppRole.patient : "superAdmin" in value ? AppRole.superAdmin : "labAdmin" in value ? AppRole.labAdmin : "phlebotomist" in value ? AppRole.phlebotomist : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Partial: null;
} | {
    Settled: null;
}): Variant_Partial_Settled {
    return "Partial" in value ? Variant_Partial_Settled.Partial : "Settled" in value ? Variant_Partial_Settled.Settled : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
} | {
    duplicateCode: null;
}): TestError {
    return "notFound" in value ? TestError.notFound : "duplicateCode" in value ? TestError.duplicateCode : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    production: null;
} | {
    test: null;
}): SystemMode {
    return "production" in value ? SystemMode.production : "test" in value ? SystemMode.test : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
}): Variant_ok_notFound {
    return "ok" in value ? Variant_ok_notFound.ok : "notFound" in value ? Variant_ok_notFound.notFound : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppUser>): Array<AppUser> {
    return value.map((x)=>from_candid_AppUser_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SampleRecord>): Array<SampleRecord> {
    return value.map((x)=>from_candid_SampleRecord_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Settlement>): Array<Settlement> {
    return value.map((x)=>from_candid_Settlement_n26(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SampleInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleInput): _SampleInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_SystemMode_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemMode): _SystemMode {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleTestItem | null): [] | [_SampleTestItem] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tests: Array<SampleTestItem | null>;
    deliveryMethod?: string;
    hospitalId: string;
    totalAmount: bigint;
    patientName: string;
    paymentType: string;
    createdByMobile: string;
    phone: string;
}): {
    tests: Array<[] | [_SampleTestItem]>;
    deliveryMethod: [] | [string];
    hospitalId: string;
    totalAmount: bigint;
    patientName: string;
    paymentType: string;
    createdByMobile: string;
    phone: string;
} {
    return {
        tests: to_candid_vec_n11(_uploadFile, _downloadFile, value.tests),
        deliveryMethod: value.deliveryMethod ? candid_some(value.deliveryMethod) : candid_none(),
        hospitalId: value.hospitalId,
        totalAmount: value.totalAmount,
        patientName: value.patientName,
        paymentType: value.paymentType,
        createdByMobile: value.createdByMobile,
        phone: value.phone
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: AppRole;
    area?: string;
    name: string;
    phone: string;
}): {
    appRole: _AppRole;
    area: [] | [string];
    name: string;
    phone: string;
} {
    return {
        appRole: to_candid_AppRole_n36(_uploadFile, _downloadFile, value.appRole),
        area: value.area ? candid_some(value.area) : candid_none(),
        name: value.name,
        phone: value.phone
    };
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Partial_Settled): {
    Partial: null;
} | {
    Settled: null;
} {
    return value == Variant_Partial_Settled.Partial ? {
        Partial_: null
    } : value == Variant_Partial_Settled.Settled ? {
        Settled: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    patient: null;
} | {
    superAdmin: null;
} | {
    labAdmin: null;
} | {
    phlebotomist: null;
} {
    return value == AppRole.patient ? {
        patient: null
    } : value == AppRole.superAdmin ? {
        superAdmin: null
    } : value == AppRole.labAdmin ? {
        labAdmin: null
    } : value == AppRole.phlebotomist ? {
        phlebotomist: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemMode): {
    production: null;
} | {
    test: null;
} {
    return value == SystemMode.production ? {
        production: null
    } : value == SystemMode.test ? {
        test: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SampleTestItem | null>): Array<[] | [_SampleTestItem]> {
    return value.map((x)=>to_candid_opt_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
